### ISSUE TITLE
Requires reregistering of watchers

### ISSUE THREAD

**Issue by petur03** [guard/rb-inotify#18]
Hi

I've been using your gem, but it's not working quite as I would expect.

It seems that I have to reregister the watcher whenever an event has occurred. So running notifier.run will loop forever, but only handle each registered event once. To continuously handle events I have to use notifier.process in a loop and run notifier.watch after process, see example below. If I omit the call to watch() in the loop, the handler will only be called the first time the file is modified.

I don't know if this is intended behaviour or not, at least I don't think it is reflected in the readme.

Thanks,
Petur

``` ruby
require 'rb-inotify'

handler = Proc.new { puts "handle" }

notifier = INotify::Notifier.new
notifier.watch("./file.txt", :modify, &handler)

loop {
  notifier.process
  notifier.watch("./file.txt", :modify, &handler)
}
```

**Comment by paoloaga** [comment]
The solution is to handle the flag ":ignored" and re-instance the notifier.watch whenever you receive one.

**Comment by ioquatix** [comment]
Now that we have test, it would be great to add a spec for this including some documentation for the correct way this should be handled.

**Comment by ioquatix** [comment]
Feel free to submit a failing PR either here or in the listen gem.
