### ISSUE TITLE
INotify::Notifier#process does not necessarily process all events

### ISSUE THREAD

**Issue by AnchorCat** [guard/rb-inotify#39]
`README.md` says of `INotify::Notifier#process`:

```
If you don't want infinite looping,
you can also block until there are available events,
process them all at once,
and then continue on your merry way
```

However, `inotify(7)` says:

```
The behavior when the buffer given to read(2) is too  small  to  return
information about the next event depends on the kernel version: in ker‐
nels before 2.6.21, read(2) returns 0;  since  kernel  2.6.21,  read(2)
fails with the error EINVAL.
```

Note that an inotify `read(2)` does not _necessarily_ need to read all events from the queue to be successful; reading at least one event is sufficient. This is not accounted for in `INotify::Notifier#read_events` (called by `#process`), which will simply return all events from a successful `read(2)`. The implementation of `#process` is therefore inconsistent with its description in `README.md`.

It is also worth noting that the RDoc for `#read_events` agrees with `README.md` about what the behaviour should be.

I am not raising a pull request yet because I don't know if this is a documentation bug (and the implementation is correct), or an implementation bug (and the description in `README.md` is the intended behaviour). Fixing the documentation is easy if that's the correct solution; if a code fix is needed, it's probably easiest to just poll `#to_io` within `#read_events` until there are no more events to read.

**Comment by ioquatix** [comment]
`#to_io` is avaialble on JRuby now. Feel free to submit a PR.
