### ISSUE TITLE
stop will not stop immediately. it will stop after the next event

### ISSUE THREAD

**Issue by shuhaowu** [guard/rb-inotify#47]
If you have no events coming in, then calling `stop` after calling `run` in a separate thread will not cause `run` to unblock. Instead, it will only stop after another event has been processed.

**Comment by shuhaowu** [comment]
Perhaps with an option the run loop could be using IO.select, or something like that.

**Comment by e2** [comment]
For completeness, here's a failing example on JRuby:

```ruby
require 'rb-inotify'

Thread.new do
  INotify::Notifier.new.tap do |notifier|
    Thread.current[:notifier] = notifier
    notifier.watch("/tmp", :modify) { |changes| puts changes.inspect }
    notifier.run
  end
end.run

sleep 3

th[:notifier].close
th.join
 # Never gets here - stuck unless an inotify event occurs
```

Any workaround possible? Any way to reliably trigger or simulate an inotify event?

**Comment by ioquatix** [comment]
I think that right now, this behaviour is outside the scope of the current implementation. The correct solution, is for notifier.run to call select with a wakeup pipe, and for stop to send a single byte down that pipe. I think this belongs elsewhere, e.g. https://github.com/socketry/async/blob/04b3fdae3fa41300777d197b09db54f7ac1d7e2d/lib/async/reactor.rb#L122
