### ISSUE TITLE
Version 0.9.7 can't be downloaded from rubygems.org

### ISSUE THREAD

**Issue by ehirsch** [guard/rb-inotify#52]
I don't know, if you can do anything about that. But wanted to let you know.

I get the following error: 

```
Could not find rb-inotify.gem (rubygems:rb-inotify:0.9.6).
     Searched in the following locations:
         http://rubygems-proxy.torquebox.org/releases/rubygems/rb-inotify/0.9.6/rb-inotify-0.9.6.gem
```

**Comment by jonnyasmar** [comment]
^ Having the same issue here.

**Comment by jpete** [comment]
^ Same issue

**Comment by matthew-lang** [comment]
^ Same here

**Comment by nex3** [comment]
I've pushed a new patch version, and it looks like it works. I guess something went awry with the upload process last time.

**Comment by ericrrath** [comment]
I think the gem can be downloaded from rubygems.org.  But the torquebox URL -- http://rubygems-proxy.torquebox.org/releases/rubygems/rb-inotify/0.9.6/rb-inotify-0.9.6.gem -- produces a response with status 403 and a body that appears to be generated by AWS.

**Comment by johnnyshields** [comment]
See this for explanation from rubygems: https://github.com/rubygems/rubygems.org/issues/1192

**Comment by ehirsch** [comment]
Thanks for the quick response! 
but while there is no 403 error any more it is now 404. The Problem remains I am afraid.

**Comment by tommybstitch** [comment]
0.9.6 has been yanked from rubygems which is causing many problems for me. Why has 0.9.6 been yanked?

**Comment by nex3** [comment]
I have indeed yanked 0.9.6 because it was broken—0.9.7 is identical except for its version number. It looks like it's still not downloadable from torquebox, though, which at this point seems like a rubygems.org issue. I don't want to upload yet another version unless I know it'll fix the problem, so I'd appreciate it if someone contacted the rubygems.org folks and figured out what's going on on their end.

**Comment by jpete** [comment]
I contacted them on 2/8, just before I posted the bump here. I have not heard anything back, and it is still down so maybe they have not gotten to it yet.

**Comment by ioquatix** [comment]
We are now on release 0.9.8 and I don't seem to be able to reproduce this issue. Thanks for your input and attention everyone and let me know if this is still an issue that requires investigation.
