### ISSUE TITLE
New child directory not being watched

### ISSUE THREAD

**Issue by phuonglm** [guard/rb-inotify#75]
Since Inotify not supported recursive so we adding all child directory to watch list. I tested case create new child directory, new event fire and that fine. but go to that child directory and create new file or directory --> nothing happen.

**Comment by ioquatix** [comment]
Can you provide a failing test case so I can reproduce locally?

**Comment by ioquatix** [comment]
@phuonglm Can you please check if this bug still occurs and can you provide a small repro/spec?

**Comment by phuonglm** [comment]
I using vagrant gatling rsync on linux machine and a got this problem. I'll try to reproduce this problem with simple ruby script
