### ISSUE TITLE
warning: rb_safe_level will be removed in Ruby 3.0

### ISSUE THREAD

**Issue by mirelon** [guard/rb-inotify#99]
When using Ruby 2.7.0, Rails 6.1.2.1, I get the following warning:

.../gems/rb-inotify-0.10.0/lib/rb-inotify/watcher.rb:66: warning: rb_safe_level will be removed in Ruby 3.0

**Comment by ioquatix** [comment]
Do you want to make a PR to remove it?

**Comment by mirelon** [comment]
If no one else, I will probably make it at the weekend.

**Comment by mirelon** [comment]
It is no issue of rb-inotify, but the ffi dependency.
I had ffi with version 1.11.2
Running `bundle update ffi` increases the ffi version to 1.12.2, which fixes the issue.

More details about ruby 2.7 compatibility:
https://github.com/ffi/ffi/blob/master/CHANGELOG.md
